# run using
version: "3.8"

services:
  bildverarbeitung:
    build:
      context: ./Bildverarbeitung
      dockerfile: ./Bildverarbeitung/Dockerfile
    image: "ws22-robotik-4-gewinnt/bildverarbeitung:local"
    devices: 
      - "/dev/video0:/dev/video0"
    ports:
      - "8090:8090"
    restart: always
    
  gamelogic:
    build:
      context: ./Spielalgorithmus
      dockerfile: ./Spielalgorithmus/Dockerfile
    image: "ws22-robotik-4-gewinnt/spielalgorithmus:local"
    ports:
      - "8093:8093"
    restart: always
    
  hardwaresteuerung:
    build:
      context: ./Hardwaresteuerung
      dockerfile: ./Hardwaresteuerung/Dockerfile
    image: "ws22-robotik-4-gewinnt/hardwaresteuerung:local"
    privileged: true
    ports:
      - "8096:8096"
    restart: always
