# run using
version: "3.8"

services:
  bildverarbeitung:
    image: ghcr.io/ws22-robotik-4-gewinnt/bildverarbeitung:main
    devices: 
      - "/dev/video0 : /dev/video0"
    ports:
      - "8090:8090"
    restart: always
    
  gamelogic:
    image: ghcr.io/ws22-robotik-4-gewinnt/spielalgorithmus:main
    ports:
      - "8093:8093"
    restart: always
    
  hardwaresteuerung:
    image: ghcr.io/ws22-robotik-4-gewinnt/hardwaresteuerung:main
    privileged: true
    ports:
      - "8096:8096"
    restart: always
